require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/schema.rb'
  TargetRubyVersion: 3.0
  SuggestExtensions: false

Metrics/AbcSize:
  Max: 17

Metrics/ClassLength:
  Enabled: 191

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/NumericLiterals:
  Enabled: false
